server:
  port: 9091
spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5444/auth'
    username: 'postgres'
    password: 'postgres'
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'

  security:
    oauth2:
      client:
        registration:
          api-client-oidc:
            provider: spring
            client-id: api-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:9091/login/oauth2/code/{registrationId}"
            scope: openid
            client-name: api-client-oidc
          api-client-authorization-code:
            provider: spring
            client-id: api-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:9091/authorized"
            scope: api.read
            client-name: api-client-authorization-code
        provider:
          spring:
            issuer-uri: http://localhost:9092

logging:
  level:
    io:
      r2dbc:
        postgresql:
          QUERY: DEBUG
          PARAM: DEBUG
    root: info
    com:
      ahmadthesis:
        auth: debug
  file:
    name: 'E:\thesis_project\auth\logs\application.log'

directory:
  image: 'E:\thesis_project\auth\upload'

time:
  zone: 'Asia/Jakarta'
  pattern: 'yyyy-MM-dd HH:mm:ss z'