server:
  port: 9091
spring:
  r2dbc:
    url: 'r2dbc:postgresql://postgres@localhost:5432/image'
    password: 'postgres'
  h2:
    console:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://auth-server:8050'

logging:
  level:
    io:
      r2dbc:
        postgresql:
          QUERY: DEBUG
          PARAM: DEBUG
    root: info
    com:
      ahmadthesis:
        image: debug
  file:
    name: 'E:\thesis_project\logs\application.log'

directory:
  image: 'E:\thesis_project\upload'

time:
  zone: 'Asia/Jakarta'
  pattern: 'yyyy-MM-dd HH:mm:ss z'