server:
  port: 9090
spring:
  r2dbc:
    url: 'r2dbc:postgresql://postgres@db:5432/image'
    password: 'postgres'
  h2:
    console:
      enabled: true

logging:
  level:
    io:
      r2dbc:
        postgresql:
          QUERY: DEBUG
          PARAM: DEBUG
    root: info
    com:
      ahmadthesis:
        image: debug
  file:
    name: '/home/ahmad/image/logs/application.log'

directory:
  image: '/home/ahmad/image/uploads'

time:
  zone: 'Asia/Jakarta'
  pattern: 'yyyy-MM-dd HH:mm:ss z'