server:
  port: 9090
spring:
#  servlet:
#    multipart:
#      max-file-size: 100MB
#      max-request-size: 100MB

  r2dbc:
    url: 'r2dbc:postgresql://postgres@db:5432/image'
    password: 'postgres'
  h2:
    console:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://auth-server:8051'

logging:
  level:
    io:
      r2dbc:
        postgresql:
          QUERY: DEBUG
          PARAM: DEBUG
    root: info
    com:
      ahmadthesis:
        image: debug
  file:
    name: '/home/ahmad/image/logs/application.log'

directory:
  image: '/home/ahmad/image/uploads'
  thumbnail: '/home/ahmad/image/uploads'

time:
  zone: 'Asia/Jakarta'
  pattern: 'yyyy-MM-dd HH:mm:ss z'

email:
  sender-address: ${AUTH_EMAIL}
  sender-password: ${AUTH_PASS}

copernicus:
  token-api: 'https://identity.dataspace.copernicus.eu/auth/realms/CDSE/protocol/openid-connect/token'
  process-api: 'https://sh.dataspace.copernicus.eu/api/v1/process'
  grant-type: ${COPERNICUS_GRANT_TYPE}
  client-id: ${COPERNICUS_CLIENT_ID}
  client-secret: ${COPERNICUS_CLIENT_SECRET}

midtrans:
  server-key: ${MIDTRANS_SERVER_KEY}