server:
  port: 9092
spring:
  db-connection:
    image: 'r2dbc:postgres://postgres:postgres@localhost:5432/image?schema=public'
    payment: 'r2dbc:postgres://postgres:postgres@localhost:5446/payment?schema=public'
#  r2dbc:
#    image-datasource:
#      url: 'r2dbc:postgresql://postgres@localhost:5432/image'
#      username: 'postgres'
#      password: 'postgres'
#    payment-datasource:
#      url: 'r2dbc:postgresql://postgres@localhost:5446/payment'
#      username: 'postgres'
#      password: 'postgres'
#  h2:
#    console:
#      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:28080/realms/${REALM_NAME}
          jwk-set-uri: http://localhost:28080/realms/${REALM_NAME}/protocol/openid-connect/certs

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot.autoconfigure.security: DEBUG
    org.springframework.boot.autoconfigure.security.oauth2: DEBUG
    io:
      r2dbc:
        postgresql:
          QUERY: DEBUG
          PARAM: DEBUG
    root: info
    com:
      ahmadthesis:
        image: debug
  file:
    name: 'D:\Thesis\logs\application.log'

directory:
  image: 'D:\Thesis\upload\image'
  thumbnail: 'D:\Thesis\upload\thumbnail'

time:
  zone: 'Asia/Jakarta'
  pattern: 'yyyy-MM-dd HH:mm:ss z'

api:
  payment:
    get-subscription-level: 'http://localhost:9093/payment'