server:
  port: 9090
spring:
  r2dbc:
    url: 'r2dbc:postgresql://postgres@localhost:5432/image'
    password: 'postgres'
  h2:
    console:
      enabled: true

directory:
  image: 'E:\thesis_project\upload'

time:
  zone: 'Asia/Jakarta'
  pattern: 'yyyy-MM-dd HH:mm:ss z'