server:
  port: 9091
spring:
  r2dbc:
    url: 'r2dbc:postgresql://postgres@localhost:5432/auth'
    password: 'postgres'
  h2:
    console:
      enabled: true

logging:
  level:
    io:
      r2dbc:
        postgresql:
          QUERY: DEBUG
          PARAM: DEBUG
    root: info
    com:
      ahmadthesis:
        auth: debug
  file:
    name: 'E:\thesis_project\auth\logs\application.log'

directory:
  image: 'E:\thesis_project\auth\upload'

time:
  zone: 'Asia/Jakarta'
  pattern: 'yyyy-MM-dd HH:mm:ss z'