server:
  port: 9096
spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5444/auth'
    username: 'postgres'
    password: 'postgres'
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'

oauth2-setup:
  uri:
    host: 'http://127.0.0.1:9096'
    login: 'http://127.0.0.1:9095/login/oauth2/code/api-client-oidc'
    authorized: 'http://127.0.0.1:9095/authorized'

logging:
  level:
    io:
      r2dbc:
        postgresql:
          QUERY: DEBUG
          PARAM: DEBUG
    root: info
    com:
      ahmadthesis:
        auth: debug
  file:
    name: '/home/ahmad/auth/logs/application.log'

directory:
  image: '/home/ahmad/auth/uploads'

time:
  zone: 'Asia/Jakarta'
  pattern: 'yyyy-MM-dd HH:mm:ss z'