server:
  port: 9093
spring:
  r2dbc:
    url: 'r2dbc:postgresql://postgres@localhost:5446/payment'
    password: 'postgres'
  h2:
    console:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:28080/realms/${REALM_NAME}
          jwk-set-uri: http://localhost:28080/realms/${REALM_NAME}/protocol/openid-connect/certs

midtrans:
  merchant-id: ${MIDTRANS_MERCHANT_ID}
  server-key: ${MIDTRANS_SERVER_KEY}
  client-key: ${MIDTRANS_CLIENT_KEY}
