version: '3'
services:
  image-be:
    ports:
      - 9090:9090
    image: image-be
    build:
      context: .
      dockerfile: Dockerfile
    container_name: image-be
    restart: always
    network_mode: compose_network
    volumes:
      - /home/ahmad/image/uploads:/home/ahmad/image/uploads